django_user_profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.get_profile, name='get_profile'),
    path('users/register/', views.RegisterFormView.as_view(), name='register'),
    path('users/login/', views.LoginFormView.as_view(), name='login'),
    path('users/all/', views.all_users, name='all_users'),
]

django_user_profiles/models.py
from django.db import models
from django.contrib.auth.models import User # Default user model.
                                            # You can change it to your custom model
from django.db.models import F
from .settings import default_avatar, default_visibility

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    creater_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    display_name = models.CharField(max_length=20, blank=True)
    bio = models.CharField(blank=True, null=True)
    avatar = models.ImageField(upload_to='avatars/', default=default_avatar)
    birth_date = models.DateField(blank=True, null=True)
    social_links = models.JSONField(blank=True, null=True)

    is_public = models.BooleanField(default=default_visibility)
    show_email = models.BooleanField(default=True)
    show_social_links = models.BooleanField(default=True)

    def save(self, *args, **kwargs): # Default value for display_name
        if not self.display_name:
            self.display_name = f"user{self.user.id}"

        super().save(*args, **kwargs)

django_user_profiles/forms.py
from django import forms
from django.contrib.auth import authenticate
from .models import User

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(
        widget=forms.PasswordInput # <input type='password' />
    )

    def clean_username(self):
        username = self.cleaned_data['username']

        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(
                'Пользователь с таким именем уже существует'
            )




class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(
        widget=forms.PasswordInput
    )

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")

        if username and password:
            user = authenticate(
                username=username,
                password=password
            )
            if user is None:
                raise forms.ValidationError(
                    "Неверный логин или пароль"
                )

        return cleaned_data

django_user_profiles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.views.generic.edit import FormView
from .models import Profile, User
from .forms import RegisterForm, LoginForm

class RegisterFormView(FormView):
    template_name = 'profiles/registration.html'
    form_class = RegisterForm
    success_url = '/profiles/users/all'

    def form_valid(self, form):
        data = form.cleaned_data
        u = User(username=data['username'])
        u.set_password(data['password'])
        u.save()

        login(self.request, u)
        return super().form_valid(form)
    
class LoginFormView(FormView):
    template_name = 'profiles/login.html'
    form_class = LoginForm
    success_url = '/profiles/users/all'

    def form_valid(self, form):
        data = form.cleaned_data
        u = authenticate(
            username=data['username'],
            password=data['password']
        )

        login(self.request, u)
        return super().form_valid(form)
    

def index(request):
    p = Profile.objects.all()

    return render(request, 'profiles/index.html', {'profiles': p})
    
    
def all_users(request):
    u = User.objects.all()
    return render(request, 'profiles/all_users.html', {'users': u})

def get_profile(request, id):

    p = Profile.objects.filter(user_id=id)

    if not p:
        return HttpResponse('404 Not Found')

    return render(request, 'profiles/profile.html', {'profile': p.get(), 'user': request.user})

django_user_profiles/templates/profiles/all_users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All users</title>
</head>
<body>
    <ul>
        {% for user in users %}
            <li>
                <a href="{% url 'profiles:get_profile' user.id  %}">ID: {{ user.id }}</a>
                <p>{{ user.username }}</p>
                <p>{{ user.password }}</p>
           </li>
        {% endfor %}
    </ul>
</body>
</html>

django_user_profiles/templates/profiles/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Profile</title>
</head>
<body>
    <form action="/profiles/add/" enctype="multipart/form-data" method="post" style="display: flex; flex-direction: column; justify-content: center; padding-left: 350px; padding-right: 350px; gap: 10px">
        {% csrf_token %}
        <input type="text" name="display_name" id="display_name" placeholder="Display name">
        <input type="email" name="email" id="email" placeholder="Email">
        <textarea name="bio" id="bio" placeholder="bio"></textarea>
        <input type="date" name="birth_date" id="birth_date" placeholder="Birth date">
        <input type="text" name="links" id="Telegram" placeholder="Telegram">
        <input type="text" name="links" id="Github" placeholder="Github">
        <input type="text" name="links" id="LinkedIn" placeholder="LinkedIn">
        <input type="file" name="avatar" id="avatar">
        <button>Send</button>
    </form>
</body>
</html>

django_user_profiles/templates/profiles/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Login</button>
    </form>
</body>
</html>

django_user_profiles/templates/profiles/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
</head>
<body>
    {% if not profile.is_public and request.user.id != profile.user_id %}
        <h1>Private profile</h1>
    {% else %}
        <h1>{{ profile.id }}</h1>
        <p>{{ profile.display_name }}</p>
        {% if request.user.id == profile.user_id %}
            <h1>ID</h1>
        {% endif %}
        <p>{{ profile.bio }}</p>
        <img src="http://127.0.0.1:8000/media/{{ profile.avatar }}">
        <p>{{ profile.birth_date }}</p>
        <p>{{ profile.social_links }}</p>
        <p>{{ profile.is_public }}</p>
        <p>{{ profile.show_email }}</p>
        <p>{{ profile.show_social_links }}</p>
    {% endif %}
</body>
</html>

django_user_profiles/templates/profiles/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>register</button>
    </form>
</body>
</html>

django_user_profiles/templates/profiles/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test</title>
</head>
<body>
    <img src="127.0.0.1:8000/media/avatars/{{ avatar }}">
</body>
</html>